kubos/kubos-cli

kubos/target.py

After switching to proxying commands to yotta - the target option gets used in many commands. If no target has been set it will default to the `stm32f407-disco-gcc` target. Just like how yotta will default to the `x86-native-<platform>` target by default.
This behavior allows us to use many of the default yotta commands but it also has a side effect of not allowing `kubos target` to list the targets if no target is set (it will just print the stm32f4 discovery target as that's the default). 
This adds a `--list` option to target so at any time, no matter if you have a target set you can always list and look at all of the available targets with `kubos target --list`.

Add --list opton for the target command

---

README.md
kubos/sdk_config.py
kubos/version.py
kubos/versions.py
module.json
setup.json

This should be the last PR before the first kubos-cli version ships.
This PR adds:
* Error checking for cases where ~/.kubos doesn't exist
* A semi-accurate and updated README to the kubos-cli repo.
* The accurate list of kubos-cli install dependencies

Check kubos src dir

---

README.md
kubos/init.py
kubos/update.py
kubos/utils/git_common.py

Added a new parameter to 'kubos init', '--linux' ('-l' for short), which will cause the SDK to copy in the kubos-linux-example project rather than the kubos-rt-example project when initializing a new SDK project.  This example is based on the kubos-csp-example, but updated to run correctly on a linux system.
I also added an '--rt' ('-r') option to balance things out.  Really it doesn't do anything, but from a UX perspective, I think it's nice to give users an option to intentionally specify that they want to create a KubOS RT project instead of a KubOS Linux project.  (It is mutually exclusive with --linux)

[KUBOS-330] Adding 'kubos init' for linux option

---

kubos/override/reimplemented_modules/cmakegen.py
kubos/override/reimplemented_modules/component.py
kubos/override/yotta_lib.py

This enables Kubos modules to surround their static lib with `-Wl,--whole-archive` and `-Wl,--no-whole-archive`, forcing the linker to keep all symbols in the static lib (needed for the additional CSP slash commands)
I tried to keep the amount of copy-pasted code to a minimum, so I first subclass and then replace the super class in override module. LMK if this works..
This pull request needs to be merged for kubostech/kubos#34
/cc @kubostech/devs

Enable modules to force link their entire static lib

---

kubos/use.py
kubos/utils/sdk_utils.py
kubos/version.py
module.json

This PR changes the `use` command to delete the globally linked modules and targets from `~/.kubos/kubos/.... before checking out and relinking a different version of the kubos source tree.
This is needed because different versions may add or more importantly remove old modules/targets. When targets are removed from the kubos source the symlinks remain in `/usr/local/yotta_...`. These "out of date" symlinks cause errors when we try to link those out of date modules/targets into projects.
The simplest way to get rid of these symlinks is to just delete the `/usr/local/lib/yotta_modules` and `/usr/local/lib/yotta_targets` directories before we link new modules and targets into those directories.
This PR also includes:
* A version bump to match what is currently uploaded in pypi
* Missing …

Purge linked modules and targets before linking new modules to the global cache

---

kubos/main.py
kubos/test/test_build.py
kubos/test/test_init.py
kubos/test/test_sdk_utils.py
kubos/test/utils.py
module.json

This is a first pass (of many) for adding unit tests to the kubos-cli.
The test_build.py is a "template" unit test which will be duplicated for each of the commands that proxy directly to yotta implementations of those commands.
This includes test for the `build` and `init` commands as well as some of the internal functions for linking and discovering modules and targets.
cc/ @kubostech/devs

KUBOS-341 Backfill unit tests

---

kubos/update.py
kubos/use.py
kubos/utils/git_utils.py

This PR adds the ability to checkout either tags or branches with the `use --branch <branch_name>` command.
It also modifies the `update` command to fetch branches and tags, rather than tags only.
cc/ @kubostech/devs

KUBOS-361 Add option to the use command to checkout specific branches or tags.

---

requirements.txt

JWT v0.3.2 was the last version to support python 2.7. Freezing on this version should not affect any functionality since yotta development has stopped.

fixing JWT version number and adding pysocks dependency for the vagrant environment

---

module.json
setup.json

Master is protected so this has to go through a PR. These are the live production changes made Friday.

Fixing jwt dependency version number, bumping version number

---

README.md
circle.yml
kubos/test/test_init.py
kubos/test/test_sdk_utils.py
module.json
requirements.txt
setup.json

This fixes some bugs in the unittests and adds some additional functionality needed to setup the CircleCI test environment to replicate the vagrant `kubos-dev` environment.

Fix CLI Unit tests and integrate with CircleCI

---

kubos/options/command.py

This fixes our error code return issue that came from how we load the subcommands at runtime.

KUBOS-363 Return the return code from subcommands when executing subcommands

---

module.json

For CI purposes we need to release a new build of the kubos-cli.
The only change for this version is returning accurate return codes from commands (which is critical for CI to work properly)

Bumping version to 0.2.2

---

kubos/utils/git_utils.py

Our tags used the vX.X.X convention initially but has dropped the 'v' and changed to X.X.X
The regex used to detect the difference in a tag and version didn't account for the change. This caused a warning message about branch stability to be printed when checking out valid and stable tags.
Another bug (That would fail for tags containing more than one digit per field (major, minor patch)) was discovered and fixed now in this PR.

KUBOS-412 Updating Regex for tag detection to prevent printing branch stability warning for tags.

---

kubos/update.py

This adds a `--latest` option to the update command. We can run `update --latest` when provisioning future versions of the vagrant environment.  
This means users can  initialize a new project in new vagrant environments without having to run any `update` or `use` commands first.

KUBOS-413 Adding latest option to update command

---

kubos/init.py
kubos/test/test_sdk_utils.py

This is a band-aid type fix for the RT build issue that occurs specifically with the MSP430 target trying to build the cmocka module (Which shouldn't be built by that target). 
When projects are created every target and module is linked into the project (Linux modules are linked into RT projects and vice versa) but theoretically the un-needed modules should not be built. There's a deeper issue that is most likely causing this but will take time to investigate. This isn't the ideal solution but fixes the build issue today.

KUBOS-399 Adding a function to remove the cmocka dependency when creating RT projects

---

kubos/utils/constants.py
kubos/utils/git_utils.py
kubos/version.py
kubos/versions.py

Adding a filter function to limit the number of minor tags displayed when printing all tags.
The Kubos repo CD process with no be tagging/releasing on every merge to master there will be lots of noise in the `kubos version` command. 
This pr filters out all but the most 3 recent minor tags and shows all major tags without any modification. The `versions` command has a `--all-versions` option to still print all minor versions.

KUBOS-438 Filter Minor tags/releases

---

circle.yml
deploy/deploy.py
deploy/release.py
requirements.txt

This is similar to #26  but deploys the builds as github releases instead of uploading them to pypi.

KUBOS-473 GitHub continuous delivery config

---

kubos/update.py

Updating the module itself from a subprocess shouldn't cause any issues as long as the existing .pyc files are not tampered with (ie. don't delete the /usr/lib/.../kubos directory or start importing new things from kubos after the update subprocess returns)
If running this from outside the vagrant environment stdin should be forwarded from the shell if sudo prompts for a password (tested on my machine). The vagrant environment has a password-less sudo config so this should never be an issue.

KUBOS-384 Adding self update functionality to the kubos-cli

---

kubos/main.py
kubos/target.py
kubos/test/integration/integration_test.py
kubos/test/test_sdk_utils.py
kubos/update.py
kubos/utils/constants.py
kubos/utils/sdk_utils.py

This also filters the available targets to a project based on its platform type. This pr adds a "platform" attribute to a project's module.json. The key has either an rt or linux value. Depending on the platform type it will only allow the corresponding target types to be set.
This includes a 1 line fix for a bug hanging around from #21 that was causing the integration test to fail.

KUBOS-406 Prevent setting "high level" targets

---

deploy/deploy.py

Without ci skipping a push to master for the bumped version in module.json it would invoke an infinite cycle of testing and releasing. 
Per the circle CI docs which i misread at first the brackets are needed around "ci skip" in the commit message.
https://circleci.com/docs/1.0/skip-a-build/

Adding brackets in commit message to get ci to skip the build for a bumped version

---

kubos/init.py
kubos/link.py
kubos/test/test_init.py

And adding unit tests for these test cases.
This cleans up how we're removing the cmocka dependency from the rt projects, and adds the same logic to the `link --all` command. This allows msp builds of cloned projects to build successfully.

Unifying the rt dependency removal logic in init and linking.

---

circle.yml
kubos/utils/sdk_utils.py

Building a yotta module within the copy of the kubos repo which is being used as the source code (set by running the kubos repo's `tools/kubos_link.py` script) causes a blackhole of nested symlinks in the `/usr/lib/local/yotta_modules` directory for that module.
This PR keeps the `kubos link -a` command from travelling down the rabbit hole by stopping if a sub-directory is named `yotta_modules` or `yotta_target` (also `build` because it's not relevant to linking so we might as well not traverse it)

Adding path checking to prevent symlink loop
